# Site information
site_name: Environmental Condition Monitoring
site_url: https://sitename.example
site_author: Christos Chatzisavvas
site_description: Environmental Condition Monitoring Documentation

# Copyright
copyright: Copyright &copy; 2025 TEXTaiLES Project

# Repository
repo_name: Environmental-Condition-Monitoring
repo_url: https://github.com/TEXTaiLES/Environmental-Condition-Monitoring

# Config
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  logo: assets/env_cond_mon_logo.png
  favicon: assets/env_cond_mon_logo.png

# Extra
extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/TEXTaiLES

extra_css:
  - stylesheets/extra.css
  
extra_javascript:
  - javascripts/extra.js

# Page
nav:
  - Home: index.md
  - Deployment: 
    - Installation Steps: deployment/installation_basic.md
